version: '3.8'

services:
  app:
    build: .
    container_name: brainAgriculture
    ports:
      - '3001:3000'
    env_file:
      - .env.docker
    depends_on:
      - db
    command: sh -c "npx prisma migrate reset --force && npm run start:prod"
    

  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
